CREATE TABLE Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Login VARCHAR(50) NOT NULL,
    Password VARCHAR(50) NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Image BLOB NULL,
    DateUpdate DATETIME NOT NULL,
    DateCreate DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
